version: '3.3'

services: 
    mysql: 
      environment: 
          MYSQL_ROOT_PASSWORD: MyDBRoot123 
          MYSQL_DATABASE: 7202Database
          MYSQL_USER: php 
          MYSQL_PASSWORD: php 
      image: mariadb:latest
      restart: always

    myphp:
      build: 
        context: ./WISP/php
        dockerfile: dockerfile
      image: php:7.4-fpm
      ports:
          - "9000:9000"
      volumes: 
          - $HOME/WISP/src/WISProject:/var/www/html
      depends_on: 
          - mysql
    
    mynginx:
      image: nginx:latest
      ports:
          - "8080:80"
      volumes: 
          - $HOME/WISP/src/nginx.ini:/etc/nginx/conf.d/default.conf
      depends_on: 
          - myphp


    phpMyAdmin:
      image: phpmyadmin/phpmyadmin:latest
      ports: 
          - "8082:80"
      environment: 
          PMA_HOST: mysql
      depends_on: 
          - mysql

